name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: write # For git operations
  pull-requests: write # For creating version PRs

jobs:
  release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Release dry run
        run: pnpm publish -r --dry-run
      - uses: actions/upload-artifact@v4
        with:
          path: |
            dist/**
            packages/create-book/dist/**

  create-version-pr:
    runs-on: ubuntu-latest
    outputs:
      has-changesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - name: Set up git
        # Note: These settings may be revoked if a GitHub App token is updated.
        run: |
          git config --global user.name 'vivliostyle-bot[bot]'
          git config --global user.email '236058695+vivliostyle-bot[bot]@users.noreply.github.com'
      - name: Create Version PR
        uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          setupGitUser: false

  release:
    needs:
      - release-dry-run
      - create-version-pr
    if: ${{ github.event_name == 'workflow_dispatch' && !fromJson(needs.create-version-pr.outputs.has-changesets) }}
    runs-on: ubuntu-latest
    environment: Production deployment
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - name: Set up git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git remote set-url origin "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git"
      - uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version-file: .nvmrc
          cache: 'pnpm'
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: pnpm install
      # - name: Release
      #   run: pnpm publish -r --access public
      #   env:
      #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
